import "./globals.css"

// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css"

import { config } from "@fortawesome/fontawesome-svg-core"
// Tell Font Awesome to skip adding the CSS automatically
// since it's already imported above
config.autoAddCss = false

//components
import { NavBar } from "./components/navBar/NavBar"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body>
                <NavBar />
                {children}
            </body>
        </html>
    )
}
